// Indian native tree catalog, global species seed (org_id NULL).
// Avenue and sacred giants, native fruits, medicinal species and timbers.
// CO₂ values are conservative field estimates (kg/tree/year at maturity),
// scaled by canopy size. Deliberately excludes common exotics (gulmohar,
// jacaranda, eucalyptus, subabul, rain tree, guava, papaya, cashew,
// frangipani). Shared by scripts/seed.ts and one-off backfills so both stay
// in sync.
export interface NativeSpeciesSeed {
  commonName: string;
  scientificName: string;
  category: "native" | "fruit" | "medicinal" | "timber";
  co2KgPerYear: number;
}

export const NATIVE_SPECIES: NativeSpeciesSeed[] = [
  { commonName: "Neem", scientificName: "Azadirachta indica", category: "native", co2KgPerYear: 12.5 },
  { commonName: "Peepal", scientificName: "Ficus religiosa", category: "native", co2KgPerYear: 15.2 },
  { commonName: "Banyan", scientificName: "Ficus benghalensis", category: "native", co2KgPerYear: 18.0 },
  { commonName: "Mango", scientificName: "Mangifera indica", category: "fruit", co2KgPerYear: 10.8 },
  { commonName: "Jamun", scientificName: "Syzygium cumini", category: "fruit", co2KgPerYear: 11.4 },
  { commonName: "Moringa", scientificName: "Moringa oleifera", category: "medicinal", co2KgPerYear: 8.6 },
  // Avenue / sacred / shade natives.
  { commonName: "Gular", scientificName: "Ficus racemosa", category: "native", co2KgPerYear: 14.6 },
  { commonName: "Pilkhan", scientificName: "Ficus virens", category: "native", co2KgPerYear: 15.0 },
  { commonName: "Arjun", scientificName: "Terminalia arjuna", category: "native", co2KgPerYear: 16.4 },
  { commonName: "Palash", scientificName: "Butea monosperma", category: "native", co2KgPerYear: 9.8 },
  { commonName: "Amaltas", scientificName: "Cassia fistula", category: "native", co2KgPerYear: 10.2 },
  { commonName: "Kachnar", scientificName: "Bauhinia variegata", category: "native", co2KgPerYear: 9.4 },
  { commonName: "Ashok", scientificName: "Polyalthia longifolia", category: "native", co2KgPerYear: 11.0 },
  { commonName: "Kadam", scientificName: "Neolamarckia cadamba", category: "native", co2KgPerYear: 13.8 },
  { commonName: "Semal", scientificName: "Bombax ceiba", category: "native", co2KgPerYear: 14.2 },
  { commonName: "Pangara", scientificName: "Erythrina variegata", category: "native", co2KgPerYear: 9.0 },
  { commonName: "Cork Tree", scientificName: "Millingtonia hortensis", category: "native", co2KgPerYear: 10.6 },
  { commonName: "Chilbil", scientificName: "Holoptelea integrifolia", category: "native", co2KgPerYear: 12.0 },
  { commonName: "Bakul", scientificName: "Mimusops elengi", category: "native", co2KgPerYear: 11.8 },
  { commonName: "Siris", scientificName: "Albizia lebbeck", category: "native", co2KgPerYear: 12.8 },
  { commonName: "Safed Siris", scientificName: "Albizia procera", category: "native", co2KgPerYear: 12.2 },
  { commonName: "Babul", scientificName: "Vachellia nilotica", category: "native", co2KgPerYear: 11.5 },
  { commonName: "Khejri", scientificName: "Prosopis cineraria", category: "native", co2KgPerYear: 10.9 },
  { commonName: "Dhok", scientificName: "Anogeissus pendula", category: "native", co2KgPerYear: 8.8 },
  { commonName: "Kusum", scientificName: "Schleichera oleosa", category: "native", co2KgPerYear: 12.4 },
  { commonName: "Tendu", scientificName: "Diospyros melanoxylon", category: "native", co2KgPerYear: 10.5 },
  { commonName: "Dhaman", scientificName: "Grewia tiliifolia", category: "native", co2KgPerYear: 9.2 },
  { commonName: "Bhojpatra", scientificName: "Betula utilis", category: "native", co2KgPerYear: 7.8 },
  // Native fruits.
  { commonName: "Bel", scientificName: "Aegle marmelos", category: "fruit", co2KgPerYear: 10.2 },
  { commonName: "Amla", scientificName: "Phyllanthus emblica", category: "fruit", co2KgPerYear: 9.0 },
  { commonName: "Kathal", scientificName: "Artocarpus heterophyllus", category: "fruit", co2KgPerYear: 13.5 },
  { commonName: "Ber", scientificName: "Ziziphus mauritiana", category: "fruit", co2KgPerYear: 8.4 },
  { commonName: "Kaitha", scientificName: "Limonia acidissima", category: "fruit", co2KgPerYear: 9.6 },
  { commonName: "Chironji", scientificName: "Buchanania lanzan", category: "fruit", co2KgPerYear: 8.0 },
  { commonName: "Lasoda", scientificName: "Cordia dichotoma", category: "fruit", co2KgPerYear: 8.8 },
  { commonName: "Khirni", scientificName: "Manilkara hexandra", category: "fruit", co2KgPerYear: 9.9 },
  { commonName: "Gab", scientificName: "Diospyros malabarica", category: "fruit", co2KgPerYear: 10.1 },
  { commonName: "Elephant Apple", scientificName: "Dillenia indica", category: "fruit", co2KgPerYear: 12.6 },
  { commonName: "Barhal", scientificName: "Artocarpus lacucha", category: "fruit", co2KgPerYear: 11.2 },
  { commonName: "Kokum", scientificName: "Garcinia indica", category: "fruit", co2KgPerYear: 8.2 },
  { commonName: "Mahua", scientificName: "Madhuca longifolia", category: "fruit", co2KgPerYear: 13.0 },
  { commonName: "Tad", scientificName: "Borassus flabellatus", category: "fruit", co2KgPerYear: 11.0 },
  { commonName: "Wild Date Palm", scientificName: "Phoenix sylvestris", category: "fruit", co2KgPerYear: 7.5 },
  { commonName: "Indian Almond", scientificName: "Terminalia catappa", category: "fruit", co2KgPerYear: 12.3 },
  { commonName: "Kaphal", scientificName: "Myrica esculenta", category: "fruit", co2KgPerYear: 7.2 },
  { commonName: "Mehal", scientificName: "Pyrus pashia", category: "fruit", co2KgPerYear: 6.8 },
  { commonName: "Chilgoza", scientificName: "Pinus gerardiana", category: "fruit", co2KgPerYear: 9.5 },
  // Medicinal natives.
  { commonName: "Harad", scientificName: "Terminalia chebula", category: "medicinal", co2KgPerYear: 11.6 },
  { commonName: "Baheda", scientificName: "Terminalia bellirica", category: "medicinal", co2KgPerYear: 12.1 },
  { commonName: "Sita Ashok", scientificName: "Saraca asoca", category: "medicinal", co2KgPerYear: 10.4 },
  { commonName: "Saptaparni", scientificName: "Alstonia scholaris", category: "medicinal", co2KgPerYear: 12.9 },
  { commonName: "Karanj", scientificName: "Pongamia pinnata", category: "medicinal", co2KgPerYear: 11.3 },
  { commonName: "Putranjiva", scientificName: "Putranjiva roxburghii", category: "medicinal", co2KgPerYear: 10.8 },
  { commonName: "Rudraksha", scientificName: "Elaeocarpus ganitrus", category: "medicinal", co2KgPerYear: 12.7 },
  { commonName: "Reetha", scientificName: "Sapindus mukorossi", category: "medicinal", co2KgPerYear: 10.0 },
  { commonName: "Khair", scientificName: "Senegalia catechu", category: "medicinal", co2KgPerYear: 9.3 },
  { commonName: "Tejpat", scientificName: "Cinnamomum tamala", category: "medicinal", co2KgPerYear: 8.5 },
  { commonName: "Curry Leaf", scientificName: "Murraya koenigii", category: "medicinal", co2KgPerYear: 5.8 },
  { commonName: "Parijat", scientificName: "Nyctanthes arbor-tristis", category: "medicinal", co2KgPerYear: 6.2 },
  { commonName: "Buransh", scientificName: "Rhododendron arboreum", category: "medicinal", co2KgPerYear: 8.9 },
  { commonName: "Indian Horse Chestnut", scientificName: "Aesculus indica", category: "medicinal", co2KgPerYear: 11.1 },
  { commonName: "Bijasal", scientificName: "Pterocarpus marsupium", category: "medicinal", co2KgPerYear: 13.2 },
  { commonName: "Pilu", scientificName: "Salvadora persica", category: "medicinal", co2KgPerYear: 7.6 },
  { commonName: "Agar", scientificName: "Aquilaria malaccensis", category: "medicinal", co2KgPerYear: 10.7 },
  // Timber natives.
  { commonName: "Teak", scientificName: "Tectona grandis", category: "timber", co2KgPerYear: 14.1 },
  { commonName: "Sal", scientificName: "Shorea robusta", category: "timber", co2KgPerYear: 16.8 },
  { commonName: "Shisham", scientificName: "Dalbergia sissoo", category: "timber", co2KgPerYear: 13.4 },
  { commonName: "Red Sanders", scientificName: "Pterocarpus santalinus", category: "timber", co2KgPerYear: 12.0 },
  { commonName: "Sandalwood", scientificName: "Santalum album", category: "timber", co2KgPerYear: 9.7 },
  { commonName: "Deodar", scientificName: "Cedrus deodara", category: "timber", co2KgPerYear: 15.5 },
  { commonName: "Chir Pine", scientificName: "Pinus roxburghii", category: "timber", co2KgPerYear: 13.9 },
  { commonName: "Haldu", scientificName: "Haldina cordifolia", category: "timber", co2KgPerYear: 12.5 },
  { commonName: "Gamhar", scientificName: "Gmelina arborea", category: "timber", co2KgPerYear: 13.1 },
  { commonName: "Saj", scientificName: "Terminalia elliptica", category: "timber", co2KgPerYear: 14.8 },
  { commonName: "Toon", scientificName: "Toona ciliata", category: "timber", co2KgPerYear: 13.6 },
  { commonName: "Rohida", scientificName: "Tecomella undulata", category: "timber", co2KgPerYear: 9.1 },
  { commonName: "Thorny Bamboo", scientificName: "Bambusa bambos", category: "timber", co2KgPerYear: 11.9 },
  { commonName: "Male Bamboo", scientificName: "Dendrocalamus strictus", category: "timber", co2KgPerYear: 11.4 },
];
